---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_26737bc5cc9e
          env:
            - name: DB_DRIVER_CLASS_NAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: driverClassName
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: url
            - name: DB_USER_ID
              valueFrom:
                secretKeyRef:
                  name: db
                  key: username
            - name: DB_USER_PW
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
            - name: JWT_VALID_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: expiredTime
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: host
            - name: SMTP_ID
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: id
            - name: SMTP_PW
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: pw
            - name: CLAIM
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: claim
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: redis
            - name: REDIS_AUTH_NUM_VALID_TIME
              valueFrom:
                secretKeyRef:
                  key: authNumValidTime
                  name: redis
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: clientId
                  name: kakao
            - name: KAKAO_LOGIN_GRANT_TYPE
              valueFrom:
                secretKeyRef:
                  key: loginGrantType
                  name: kakao
            - name: KAKAO_LOGIN_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  key: loginRedirectUrl
                  name: kakao
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              # 해당 /api 가 안  뚫려있으면 Ready 가 안되요.
              path: /api/test
              port: 8080
        - name: redis
          image: redis:7.2.2
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    # selector 가 app name 에 맞도록 주위해주세요.
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
